sonar.projectKey=jmseraphin_Smarthotel
sonar.organization=jmseraphin

sonar.sources=.
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**